import { GUI_IPC_CHANNELS } from './ipc.js'

export function createRendererScript(): string {
  const channelsJson = JSON.stringify(GUI_IPC_CHANNELS)
  return `(() => {
  const channels = ${channelsJson};
  const { ipcRenderer } = require('electron');
  const state = { repos: [], repo: null, issue: null, repoCache: new Map(), issueCache: new Map(), commentCache: new Map(), requestSeq: { repos: 0, issues: 0, issue: 0, run: 0 }, busy: { repos: false, issues: false, issue: false, run: false }, filter: '', activeIssueIndex: 0, activeRepoIndex: 0, activeList: 'issues', runResult: null, runLog: 'No run yet.', progressText: 'Idle', paletteOpen: false, helpOpen: false, issueListCollapsed: false, mapOutputCollapsed: false, commentsCollapsed: false, fullscreenPanel: null, issueLoading: false, optimizing: false, pendingOptimization: null, favoriteRepoKeys: new Set(), currentIssueLoadRequestId: null, settingsOpen: false, cacheStatus: 'cold' };
  const ROW_HEIGHT = 68;
  const overscan = 5;
  const $ = (id) => document.getElementById(id);
  const repoKey = (repo) => repo ? repo.owner + '/' + repo.name : '';
  const issueKey = (repo, number) => repoKey(repo) + '#' + number;
  const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
  const invoke = (channel, ...args) => ipcRenderer.invoke(channel, ...args);
  const setStatus = (message, variant = 'info') => { if (message) $('progress-label').textContent = message; };
  function setCacheStatus(status) { state.cacheStatus = status; const node = $('cache-status'); if (node) node.textContent = 'Cache: ' + status; }
  const isTypingTarget = (target) => target instanceof HTMLInputElement || target instanceof HTMLTextAreaElement || target?.isContentEditable;
  const currentIssues = () => state.repo ? (state.repoCache.get(repoKey(state.repo)) || []) : [];
  const filteredRepos = () => sortReposForDisplay(state.repos.filter((repo) => repoKey(repo).toLowerCase().includes(state.filter.toLowerCase())));
  const lastSelectedRepo = 'minion:lastSelectedRepo';
  const repoListCacheKey = 'minion:repoListCache';
  const issueListCachePrefix = 'minion:issueListCache:';
  const issueDetailCachePrefix = 'minion:issueDetailCache:';
  const issueCommentsCachePrefix = 'minion:issueCommentsCache:';
  const favoriteReposCacheKey = 'minion:favoriteRepos';
  const ISSUE_PAGE_SIZE = 50;
  function mergeRepos(...groups) { const seen = new Set(); const repos = []; for (const group of groups) { for (const repo of (group || [])) { if (!repo?.owner || !repo?.name) continue; const key = repoKey(repo); if (seen.has(key)) continue; seen.add(key); repos.push({ owner: repo.owner, name: repo.name }); } } return repos; }
  function mergeIssues(...groups) { const seen = new Set(); const issues = []; for (const group of groups) { for (const issue of (group || [])) { if (!issue?.number) continue; if (seen.has(issue.number)) continue; seen.add(issue.number); issues.push({ number: issue.number, title: issue.title || '', labels: issue.labels || [] }); } } return issues; }
  function loadCachedRepos() { try { const raw = localStorage.getItem(repoListCacheKey); if (!raw) return false; const parsed = JSON.parse(raw); if (!Array.isArray(parsed)) return false; state.repos = mergeRepos(state.repos, parsed); return state.repos.length > 0; } catch { return false; } }
  function saveCachedRepos(repos) { try { localStorage.setItem(repoListCacheKey, JSON.stringify((repos || []).slice(0, 500))); } catch {} }
  function loadFavoriteRepos() { try { const raw = localStorage.getItem(favoriteReposCacheKey); const values = raw ? JSON.parse(raw) : []; state.favoriteRepoKeys = new Set(Array.isArray(values) ? values : []); } catch { state.favoriteRepoKeys = new Set(); } }
  function saveFavoriteRepos() { try { localStorage.setItem(favoriteReposCacheKey, JSON.stringify([...state.favoriteRepoKeys])); } catch {} }
  function sortReposForDisplay(repos) { return [...repos].sort((a, b) => Number(state.favoriteRepoKeys.has(repoKey(b))) - Number(state.favoriteRepoKeys.has(repoKey(a))) || repoKey(a).localeCompare(repoKey(b))); }
  function toggleFavoriteRepo() { if (!state.repo) return setStatus('Select a repo first', 'warning'); const key = repoKey(state.repo); if (state.favoriteRepoKeys.has(key)) state.favoriteRepoKeys.delete(key); else state.favoriteRepoKeys.add(key); saveFavoriteRepos(); renderRepos(); progress(state.favoriteRepoKeys.has(key) ? 'Repo pinned' : 'Repo unpinned'); }
  function issueListCacheKey(repo) { return issueListCachePrefix + repoKey(repo); }
  function issueDetailCacheKey(repo, number) { return issueDetailCachePrefix + issueKey(repo, number); }
  function issueCommentsCacheKey(repo, number) { return issueCommentsCachePrefix + issueKey(repo, number); }
  function loadCachedIssues(repo) { try { const raw = localStorage.getItem(issueListCacheKey(repo)); if (!raw) return false; const parsed = JSON.parse(raw); if (!Array.isArray(parsed?.issues)) return false; state.repoCache.set(repoKey(repo), mergeIssues(state.repoCache.get(repoKey(repo)) || [], parsed.issues)); setCacheStatus('cached'); return true; } catch { return false; } }
  function getCachedIssuePageEtags(repo) { try { const raw = localStorage.getItem(issueListCacheKey(repo)); if (!raw) return {}; const parsed = JSON.parse(raw); return parsed?.pageEtags || {}; } catch { return {}; } }
  function saveCachedIssues(repo, issues, pageEtags = getCachedIssuePageEtags(repo)) { try { localStorage.setItem(issueListCacheKey(repo), JSON.stringify({ savedAt: Date.now(), issues: (issues || []).slice(0, 1000), pageEtags })); setCacheStatus('fresh'); } catch {} }
  function loadCachedIssueDetail(repo, number) { try { const raw = localStorage.getItem(issueDetailCacheKey(repo, number)); if (!raw) return null; const detail = JSON.parse(raw); if (!detail?.number) return null; state.issueCache.set(issueKey(repo, number), detail); setCacheStatus('cached'); return detail; } catch { return null; } }
  function saveCachedIssueDetail(repo, number, detail) { try { localStorage.setItem(issueDetailCacheKey(repo, number), JSON.stringify(detail)); } catch {} }
  function loadCachedIssueComments(repo, number) { try { const raw = localStorage.getItem(issueCommentsCacheKey(repo, number)); if (!raw) return null; const comments = JSON.parse(raw); if (!Array.isArray(comments)) return null; state.commentCache.set(issueKey(repo, number), comments); setCacheStatus('cached'); return comments; } catch { return null; } }
  function saveCachedIssueComments(repo, number, comments) { try { localStorage.setItem(issueCommentsCacheKey(repo, number), JSON.stringify((comments || []).slice(-200))); } catch {} }
  function clearGithubCache() { for (const key of Object.keys(localStorage)) { if (key.startsWith('minion:repoListCache') || key.startsWith(issueListCachePrefix) || key.startsWith(issueDetailCachePrefix) || key.startsWith(issueCommentsCachePrefix)) localStorage.removeItem(key); } state.repoCache.clear(); state.issueCache.clear(); state.commentCache.clear(); setCacheStatus('cleared'); renderAll(); }
  function renderSettingsDialog() { const dialog = $('settings-dialog'); if (!dialog) return; dialog.classList.toggle('hidden', !state.settingsOpen); const pinned = $('settings-pinned-repos'); if (pinned) pinned.textContent = [...state.favoriteRepoKeys].sort().join('\n') || 'No pinned repos yet.'; }
  function cancelStaleIssueLoads() { if (state.currentIssueLoadRequestId) void invoke(channels.cancelRequest, state.currentIssueLoadRequestId); state.currentIssueLoadRequestId = null; state.requestSeq.issues += 1; state.busy.issues = false; }
  function parseRepoSlugInput(value) { const parts = String(value || '').trim().split('/'); return parts.length === 2 && parts[0] && parts[1] && !parts[0].includes(' ') && !parts[1].includes(' ') ? { owner: parts[0], name: parts[1] } : null; }
  function selectRepoFromInput() { const repo = parseRepoSlugInput($('repo-search').value); if (!repo) return false; void selectRepo(repo.owner, repo.name); $('repo-dropdown-layer').classList.add('hidden'); return true; }
  function positionRepoDropdown() { const input = $('repo-search'); const dropdown = $('repo-dropdown-layer'); const rect = input.getBoundingClientRect(); dropdown.style.left = rect.left + 'px'; dropdown.style.top = (rect.bottom + 4) + 'px'; dropdown.style.width = rect.width + 'px'; }
  function restoreLastSelectedRepo() { try { const raw = localStorage.getItem(lastSelectedRepo); if (!raw) return false; const repo = JSON.parse(raw); if (!repo?.owner || !repo?.name) return false; void selectRepo(repo.owner, repo.name); return true; } catch { return false; } }
  function progress(message, active = false) { state.progressText = message; $('progress-label').textContent = message; const bar = $('global-progress'); if (active) bar.removeAttribute('value'); else bar.value = 1; }
  function relativeTime(iso) { const ms = Date.now() - new Date(iso).getTime(); if (!Number.isFinite(ms)) return ''; const minutes = Math.max(0, Math.floor(ms / 60000)); if (minutes < 1) return 'just now'; if (minutes < 60) return minutes + 'm ago'; const hours = Math.floor(minutes / 60); return hours < 24 ? hours + 'h ago' : Math.floor(hours / 24) + 'd ago'; }
  function renderVirtualList(container, items, rowHeight, renderRow, activeIndex = -1) {
    const scrollTop = container.scrollTop;
    const viewport = container.clientHeight || 420;
    const start = Math.max(0, Math.floor(scrollTop / rowHeight) - overscan);
    const end = Math.min(items.length, Math.ceil((scrollTop + viewport) / rowHeight) + overscan);
    const fragment = document.createDocumentFragment();
    const topSpacer = document.createElement('div');
    topSpacer.style.height = String(start * rowHeight) + 'px';
    const bottomSpacer = document.createElement('div');
    bottomSpacer.style.height = String(Math.max(0, (items.length - end) * rowHeight)) + 'px';
    fragment.appendChild(topSpacer);
    for (let index = start; index < end; index += 1) fragment.appendChild(renderRow(items[index], index, index === activeIndex));
    fragment.appendChild(bottomSpacer);
    container.replaceChildren(fragment);
  }
  function makeRepoRow(repo, index, active) { const row = document.createElement('button'); row.type = 'button'; row.className = 'virtual-row' + (active ? ' active-row' : ''); row.dataset.action = 'select-repo'; row.dataset.index = String(index); row.dataset.owner = repo.owner; row.dataset.name = repo.name; const star = state.favoriteRepoKeys.has(repoKey(repo)) ? '★ ' : ''; row.innerHTML = '<div class="card-title">' + star + escapeHtml(repoKey(repo)) + '</div><div class="card-meta">repository</div>'; return row; }
  function makeIssueRow(issue, index, active) { const row = document.createElement('button'); row.type = 'button'; row.className = 'virtual-row' + (active ? ' active-row' : ''); row.dataset.action = 'select-issue'; row.dataset.index = String(index); row.dataset.number = String(issue.number); const labels = (issue.labels || []).slice(0, 3).map((label) => '<span class="pill">' + escapeHtml(label) + '</span>').join(''); row.innerHTML = '<div class="card-title">#' + issue.number + ' ' + escapeHtml(issue.title) + '</div><div class="pill-row">' + labels + '</div>'; return row; }
  function renderRepos() { const box = $('repo-dropdown-list'); if (state.busy.repos && state.repos.length === 0) { box.innerHTML = '<div class="loading-state">Loading repos…</div>'; return; } const repos = filteredRepos(); if (repos.length === 0) { box.innerHTML = '<div class="empty-state">No repos found. Type owner/name and press Enter.</div>'; return; } renderVirtualList(box, repos, ROW_HEIGHT, makeRepoRow, state.activeRepoIndex); }
  function renderIssues() { const box = $('issue-list'); $('selected-repo-label').textContent = state.repo ? repoKey(state.repo) : 'Select a repo'; if (!state.repo) { box.innerHTML = '<div class="empty-state">Use / to search repos, then Enter.</div>'; return; } if (state.busy.issues && currentIssues().length === 0) { box.innerHTML = '<div class="loading-state">Loading issues…</div>'; return; } const issues = currentIssues(); if (issues.length === 0) { box.innerHTML = '<div class="empty-state">No open issues.</div>'; return; } renderVirtualList(box, issues, ROW_HEIGHT, makeIssueRow, state.activeIssueIndex); }
  function renderIssueDetail() { const hasIssue = Boolean(state.issue); $('issue-title').value = hasIssue ? state.issue.title : ''; $('issue-body').value = hasIssue ? state.issue.body : ''; $('detail-title').textContent = hasIssue ? '#' + state.issue.number + ' ' + state.issue.title : 'New issue'; $('save-issue').textContent = hasIssue ? 'Save' : 'Create'; $('close-issue').disabled = !hasIssue; $('post-comment').disabled = !hasIssue; $('start-run').disabled = !hasIssue || state.busy.run; }
  function renderComments() { const box = $('comments-list'); if (!state.repo || !state.issue) { box.innerHTML = '<div class="empty-state">Open an issue for comments.</div>'; return; } const comments = state.commentCache.get(issueKey(state.repo, state.issue.number)) || []; if (comments.length === 0) { box.innerHTML = '<div class="empty-state">No comments.</div>'; return; } const fragment = document.createDocumentFragment(); for (const comment of comments) { const card = document.createElement('article'); card.className = 'comment-card'; card.innerHTML = '<div class="card-title">@' + escapeHtml(comment.author || 'unknown') + ' <span class="card-meta">' + relativeTime(comment.createdAt) + '</span></div><div>' + escapeHtml(comment.body) + '</div>'; fragment.appendChild(card); } box.replaceChildren(fragment); }
  function renderRunSummary(result, runLog) { const summary = $('run-summary'); if (!result) { summary.innerHTML = state.busy.run ? '<div class="loading-state">MAP is running…</div>' : '<div class="empty-state">Detailed model trace requires MAP telemetry support.</div>'; $('run-log').textContent = runLog; return; } const status = result.success ? 'success' : 'error'; summary.innerHTML = '<div class="result-grid"><div class="result-card"><div class="card-meta">Status</div><span class="status-chip ' + status + '">' + (result.success ? 'Succeeded' : 'Failed') + '</span></div><div class="result-card"><div class="card-meta">PR URL</div><div>' + escapeHtml(result.prUrl || 'No PR') + '</div></div><div class="result-card"><div class="card-meta">Files changed</div><div>' + escapeHtml((result.filesChanged || []).join(', ') || 'none') + '</div></div></div><div class="empty-state">Detailed model trace requires MAP telemetry support.</div>'; $('run-log').textContent = JSON.stringify(result, null, 2); }
  function renderRunPanel() { $('start-run').disabled = !state.repo || !state.issue || state.busy.run; renderRunSummary(state.runResult, state.runLog); }
  function collectOptimizationContext(target) { const key = state.repo && state.issue ? issueKey(state.repo, state.issue.number) : ''; const comments = key ? (state.commentCache.get(key) || []).map((comment) => '@' + (comment.author || 'unknown') + ': ' + comment.body) : []; return { target, repo: repoKey(state.repo), issueNumber: state.issue?.number, issueUrl: state.issue?.url, labels: state.issue?.labels || [], comment: $('comment-body').value, comments }; }
  function renderOptimizationDialog() { const dialog = $('optimization-dialog'); const pending = state.pendingOptimization; dialog.classList.toggle('hidden', pending === null); if (!pending) return; $('optimization-dialog-title').textContent = pending.target === 'comment' ? 'Update comment with MAP suggestion?' : 'Update description with MAP suggestion?'; $('optimization-dialog-copy').textContent = pending.target === 'comment' ? 'Review the optimized comment before replacing the composer text.' : 'Review the optimized issue description before replacing the current draft.'; $('optimization-preview').value = pending.text; $('apply-optimization').textContent = pending.target === 'comment' ? 'Update comment draft' : 'Update description draft'; }
  function closeOptimizationDialog() { state.pendingOptimization = null; renderOptimizationDialog(); }
  function applyOptimization() { if (!state.pendingOptimization) return; state.pendingOptimization.text = $('optimization-preview').value; if (state.pendingOptimization.target === 'description') { $('issue-body').value = state.pendingOptimization.text; progress('Description draft updated'); } else { $('comment-body').value = state.pendingOptimization.text; progress('Comment draft updated'); } closeOptimizationDialog(); }
  async function optimizeText(target) { const title = $('issue-title').value.trim(); const body = $('issue-body').value; const source = target === 'comment' ? $('comment-body').value : body; if (!source.trim()) return setStatus(target === 'comment' ? 'Comment is empty' : 'Description is empty', 'warning'); state.optimizing = true; progress(target === 'comment' ? 'Optimizing comment with MAP…' : 'Optimizing description with MAP…', true); try { const context = collectOptimizationContext(target); const result = await invoke(channels.polish, title, body, context); if (!result) { progress('MAP suggested no changes'); return; } const text = target === 'comment' ? (result.comment || result.body || source) : (result.body || source); state.pendingOptimization = { target, title: result.title || title, text }; renderOptimizationDialog(); progress('Review MAP suggestion'); } catch (err) { setStatus(err.message || String(err), 'error'); progress('MAP optimization failed'); } finally { state.optimizing = false; } }
  function toggleComments() { state.commentsCollapsed = !state.commentsCollapsed; renderAll(); }
  function toggleFullscreenPanel(panel) { if (panel === 'map') { state.mapOutputCollapsed = false; state.commentsCollapsed = true; } state.fullscreenPanel = state.fullscreenPanel === panel ? null : panel; renderAll(); }
  function toggleIssueList() { state.issueListCollapsed = !state.issueListCollapsed; renderAll(); }
  function toggleMapOutput() { state.mapOutputCollapsed = !state.mapOutputCollapsed; if (!state.mapOutputCollapsed) state.commentsCollapsed = true; renderAll(); }
  function renderOverlays() { renderSettingsDialog(); $('issue-list-arrow').textContent = state.issueListCollapsed ? '▶' : '▼'; $('map-output-arrow').textContent = state.mapOutputCollapsed ? '▶' : '▼'; $('comments-arrow').textContent = state.commentsCollapsed ? '▶' : '▼'; $('toggle-comments').setAttribute('aria-expanded', String(!state.commentsCollapsed)); $('toggle-map-output').setAttribute('aria-expanded', String(!state.mapOutputCollapsed)); $('toggle-issue-list').setAttribute('aria-expanded', String(!state.issueListCollapsed)); $('command-palette').classList.toggle('hidden', !state.paletteOpen); $('shortcut-help').classList.toggle('hidden', !state.helpOpen); $('repo-dropdown-layer').classList.toggle('hidden', document.activeElement !== $('repo-search')); document.body.classList.toggle('issue-list-collapsed', state.issueListCollapsed); document.body.classList.toggle('map-output-collapsed', state.mapOutputCollapsed); document.body.classList.toggle('comments-collapsed', state.commentsCollapsed); document.body.classList.toggle('issue-loading', state.issueLoading); document.body.classList.toggle('fullscreen-issues', state.fullscreenPanel === 'issues'); document.body.classList.toggle('fullscreen-editor', state.fullscreenPanel === 'editor'); document.body.classList.toggle('fullscreen-map', state.fullscreenPanel === 'map'); }
  function renderAll() { renderRepos(); renderIssues(); renderIssueDetail(); renderComments(); renderRunPanel(); renderOverlays(); renderOptimizationDialog(); }
  async function loadRepos(force = false) { const seq = ++state.requestSeq.repos; if (!force && state.repos.length > 0) return renderRepos(); if (!force) loadCachedRepos(); state.busy.repos = true; setCacheStatus('refreshing'); progress('Loading repos…', true); renderRepos(); try { if (!force) { const configuredRepos = await invoke(channels.listRepos, { includeApi: false }); if (seq !== state.requestSeq.repos) return; state.repos = mergeRepos(state.repos, configuredRepos); if (configuredRepos.length > 0) { progress('Configured repos loaded'); renderRepos(); } } const repos = await invoke(channels.listRepos, { includeApi: true }); if (seq !== state.requestSeq.repos) return; state.repos = mergeRepos(repos); saveCachedRepos(state.repos); setCacheStatus('fresh'); progress('Repos loaded');  } catch (err) { setStatus(err.message || String(err), 'error'); setCacheStatus('error'); progress('Repo load failed'); } finally { if (seq === state.requestSeq.repos) state.busy.repos = false; renderRepos(); } }
  async function selectRepo(owner, name) { cancelStaleIssueLoads(); state.repo = { owner, name }; try { localStorage.setItem(lastSelectedRepo, JSON.stringify(state.repo)); } catch {} state.issue = null; state.activeIssueIndex = 0; state.runResult = null; state.runLog = 'No run yet.'; renderAll(); await loadIssues(state.repo); }
  async function loadIssues(repo, force = false) { const key = repoKey(repo); const seq = ++state.requestSeq.issues; const requestId = key + ':' + seq; state.currentIssueLoadRequestId = requestId; const pageEtags = force ? {} : getCachedIssuePageEtags(repo); if (!force) { loadCachedIssues(repo); if (state.repoCache.has(key)) renderIssues(); } state.busy.issues = true; setCacheStatus(state.repoCache.has(key) ? 'refreshing' : 'cold'); progress('Loading issues…', true); renderIssues(); let page = 1; let mergedIssues = force ? [] : (state.repoCache.get(key) || []); try { while (true) { const result = await invoke(channels.listOpenIssuesPage, repo.owner, repo.name, { page, perPage: ISSUE_PAGE_SIZE, etag: pageEtags[String(page)], requestId }); if (seq !== state.requestSeq.issues) return; if (result.notModified) { setCacheStatus('unchanged'); progress('Issues unchanged' + (typeof result.durationMs === 'number' ? ' in ' + result.durationMs + 'ms' : '')); break; } if (result.etag) pageEtags[String(page)] = result.etag; mergedIssues = mergeIssues(mergedIssues, result.issues || []); state.repoCache.set(key, mergedIssues); saveCachedIssues(repo, mergedIssues, pageEtags); progress('Loaded ' + mergedIssues.length + ' issues' + (typeof result.durationMs === 'number' ? ' in ' + result.durationMs + 'ms' : '')); renderIssues(); if (!result.hasNextPage) break; page = (result.page || page) + 1; } } catch (err) { if (err?.name === 'AbortError') return; setStatus(err.message || String(err), 'error'); state.issueLoading = false; setCacheStatus('error'); progress('Issue load failed'); } finally { if (seq === state.requestSeq.issues) { state.busy.issues = false; state.currentIssueLoadRequestId = null; } renderIssues(); } }
  async function selectIssue(number) { if (!state.repo) return; const key = issueKey(state.repo, number); const seq = ++state.requestSeq.issue; loadCachedIssueDetail(state.repo, number); loadCachedIssueComments(state.repo, number); state.issueLoading = true; renderOverlays(); progress('Loading issue…', true); try { const issuePromise = state.issueCache.has(key) ? Promise.resolve(state.issueCache.get(key)) : invoke(channels.getIssue, state.repo.owner, state.repo.name, number); const commentsPromise = state.commentCache.has(key) ? Promise.resolve(state.commentCache.get(key)) : invoke(channels.listComments, state.repo.owner, state.repo.name, number); const [issue, comments] = await Promise.all([issuePromise, commentsPromise]); if (seq !== state.requestSeq.issue) return; state.issueCache.set(key, issue); saveCachedIssueDetail(state.repo, number, issue); state.issue = issue; state.commentCache.set(key, comments); saveCachedIssueComments(state.repo, number, comments); state.runResult = null; state.runLog = 'No run yet.'; state.issueLoading = false; setCacheStatus('fresh'); progress('Issue loaded'); } catch (err) { setStatus(err.message || String(err), 'error'); state.issueLoading = false; setCacheStatus('error'); progress('Issue load failed'); } finally { renderAll(); } }
  async function saveIssue() { if (!state.repo) return setStatus('Select a repo first', 'warning'); const title = $('issue-title').value.trim(); const body = $('issue-body').value; if (!title) return setStatus('Title required', 'warning'); progress('Saving issue…', true); if (state.issue) { await invoke(channels.updateIssue, state.repo.owner, state.repo.name, state.issue.number, title, body); state.issue = { ...state.issue, title, body }; state.issueCache.set(issueKey(state.repo, state.issue.number), state.issue); } else { const created = await invoke(channels.createIssue, state.repo.owner, state.repo.name, title, body, []); await loadIssues(state.repo, true); await selectIssue(created.number); } progress('Issue saved'); renderAll(); }
  async function postComment() { if (!state.repo || !state.issue) return setStatus('Open an issue first', 'warning'); const body = $('comment-body').value.trim(); if (!body) return setStatus('Comment is empty', 'warning'); progress('Posting comment…', true); await invoke(channels.postComment, state.repo.owner, state.repo.name, state.issue.number, body); $('comment-body').value = ''; state.commentCache.delete(issueKey(state.repo, state.issue.number)); await selectIssue(state.issue.number); progress('Comment posted'); }
  async function closeIssue() { if (!state.repo || !state.issue) return setStatus('Open an issue first', 'warning'); progress('Closing issue…', true); await invoke(channels.closeIssue, state.repo.owner, state.repo.name, state.issue.number); state.issue = null; await loadIssues(state.repo, true); progress('Issue closed'); renderAll(); }
  async function startRun() { if (!state.repo || !state.issue) return setStatus('Open an issue first', 'warning'); const seq = ++state.requestSeq.run; state.busy.run = true; state.runLog = 'Running MAP for issue #' + state.issue.number + '…'; progress('Running MAP…', true); renderRunPanel(); try { const result = await invoke(channels.runIssue, state.repo, state.issue.number); if (seq !== state.requestSeq.run) return; state.runResult = result; progress('MAP run finished'); } catch (err) { state.runLog = err.stack || err.message || String(err); setStatus(err.message || String(err), 'error'); progress('MAP run failed'); } finally { if (seq === state.requestSeq.run) state.busy.run = false; renderRunPanel(); } }
  function openIssueByIndex(index) { const issue = currentIssues()[index]; if (issue) return selectIssue(issue.number); }
   function moveIssue(delta) { const issues = currentIssues(); if (issues.length === 0) return; state.activeIssueIndex = Math.max(0, Math.min(issues.length - 1, state.activeIssueIndex + delta)); renderIssues(); void openIssueByIndex(state.activeIssueIndex); }
  function openActiveIssue() { void openIssueByIndex(state.activeIssueIndex); }
  function createIssueFromComposer() { return saveIssue(); }
  async function createAndRunFromComposer() { await saveIssue(); if (state.issue) await startRun(); }
  function createNewIssue() { state.issue = null; $('issue-title').focus(); renderAll(); }
  function handleGlobalKeydown(event) { if ((event.metaKey || event.ctrlKey) && ['a', 'c', 'v', 'x'].includes(event.key.toLowerCase())) return; if (event.key === 'Enter' && (event.metaKey || event.ctrlKey)) { event.preventDefault(); void createIssueFromComposer(); return; } if (event.key.toLowerCase() === 'r' && (event.metaKey || event.ctrlKey)) { event.preventDefault(); void createAndRunFromComposer(); return; } if (event.key.toLowerCase() === 'k' && (event.metaKey || event.ctrlKey)) { event.preventDefault(); state.paletteOpen = true; renderOverlays(); return; } if (event.key === 'Escape') { state.paletteOpen = false; state.helpOpen = false; closeOptimizationDialog(); renderOverlays(); return; } if (event.key === 'Enter' && document.activeElement === $('repo-search')) { event.preventDefault(); if (selectRepoFromInput()) return; } if (isTypingTarget(event.target)) return; if (event.key === '?') { state.helpOpen = true; renderOverlays(); return; } if (event.key === '/') { event.preventDefault(); $('repo-search').focus(); return; } if (event.key === 'j' || event.key === 'ArrowDown') { event.preventDefault(); moveIssue(1); return; } if (event.key === 'k' || event.key === 'ArrowUp') { event.preventDefault(); moveIssue(-1); return; } if (event.key === 'Enter' || event.key.toLowerCase() === 'o') { event.preventDefault(); openActiveIssue(); return; } if (event.key.toLowerCase() === 'c') { createNewIssue(); return; } if (event.key.toLowerCase() === 'm') { $('comment-body').focus(); return; } if (event.key === '[') { toggleIssueList(); return; } if (event.key === ']') { toggleMapOutput(); return; } if (event.key.toLowerCase() === 'r') { void loadRepos(true); if (state.repo) void loadIssues(state.repo, true); return; } if (event.key.toLowerCase() === 'x') { void closeIssue().catch((err) => setStatus(err.message || String(err), 'error')); } }
  document.addEventListener('click', (event) => { const target = event.target.closest('[data-action]'); if (!target) return; const action = target.dataset.action; if (action === 'toggle-comments') toggleComments(); if (action === 'open-settings') { state.settingsOpen = true; renderSettingsDialog(); } if (action === 'close-settings') { state.settingsOpen = false; renderSettingsDialog(); } if (action === 'clear-github-cache') clearGithubCache(); if (action === 'toggle-favorite-repo') toggleFavoriteRepo(); if (action === 'fullscreen-issues') toggleFullscreenPanel('issues'); if (action === 'fullscreen-editor') toggleFullscreenPanel('editor'); if (action === 'fullscreen-map') toggleFullscreenPanel('map'); if (action === 'toggle-issue-list') toggleIssueList(); if (action === 'toggle-map-output') toggleMapOutput(); if (action === 'refresh-repos') void loadRepos(true); if (action === 'refresh-issues' && state.repo) void loadIssues(state.repo, true); if (action === 'select-repo') void selectRepo(target.dataset.owner, target.dataset.name); if (action === 'select-issue') { state.activeIssueIndex = Number(target.dataset.index || 0); void selectIssue(Number(target.dataset.number)); } if (action === 'optimize-description') void optimizeText('description'); if (action === 'optimize-comment') void optimizeText('comment'); if (action === 'apply-optimization') applyOptimization(); if (action === 'cancel-optimization') closeOptimizationDialog(); if (action === 'save-issue') void saveIssue().catch((err) => setStatus(err.message || String(err), 'error')); if (action === 'post-comment') void postComment().catch((err) => setStatus(err.message || String(err), 'error')); if (action === 'close-issue') void closeIssue().catch((err) => setStatus(err.message || String(err), 'error')); if (action === 'start-run') void startRun(); if (action === 'close-overlay') { state.paletteOpen = false; state.helpOpen = false; closeOptimizationDialog(); renderOverlays(); } });
  document.addEventListener('keydown', handleGlobalKeydown);
  $('repo-search').addEventListener('input', (event) => { state.filter = event.target.value; state.activeRepoIndex = 0; renderRepos(); positionRepoDropdown(); $('repo-dropdown-layer').classList.remove('hidden'); });
  $('repo-search').addEventListener('focus', () => { renderRepos(); positionRepoDropdown(); $('repo-dropdown-layer').classList.remove('hidden'); });
  $('repo-dropdown-list').addEventListener('scroll', renderRepos);
  $('issue-list').addEventListener('scroll', renderIssues);
  loadFavoriteRepos(); renderAll(); void loadRepos().then(() => { restoreLastSelectedRepo(); });
})();`
}
