import { spawnSync } from 'node:child_process'
import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { createInkPrompt } from './ink-prompt.js'
import type { RepoConfig } from '../types/index.js'

interface OnboardingAnswers {
  token?: string
  repos: RepoConfig[]
  maxIssuesPerRun: number
}

export interface OnboardingOptions {
  configPath: string
  envPath?: string
  cwd?: string
  interactive?: boolean
  force?: boolean
  output?: Pick<Console, 'log' | 'warn' | 'error'>
  prompt?: (question: string) => Promise<string>
  commandExists?: (command: string) => boolean
}

function renderEnvTemplate(token?: string): string {
  return [
    '# GitHub personal access token with repo scope',
    `GITHUB_TOKEN=${token ?? ''}`,
    '',
  ].join('\n')
}

function renderRepoBlock(repo: RepoConfig): string[] {
  const lines = [
    `  - owner: ${repo.owner}`,
    `    name: ${repo.name}`,
    `    defaultBranch: ${repo.defaultBranch ?? 'main'}`,
  ]

  if (repo.testCommand !== undefined) {
    lines.push(`    testCommand: ${repo.testCommand}`)
  }

  return lines
}

function renderConfigTemplate(answers: OnboardingAnswers): string {
  return [
    '# minion configuration',
    '# Generated by `minion --onboard`.',
    '',
    '# Repositories to process',
    'repos:',
    ...answers.repos.flatMap(renderRepoBlock),
    '',
    '# Process one issue at a time by default until the workflow is proven in your environment.',
    `maxIssuesPerRun: ${answers.maxIssuesPerRun}`,
    '',
    '# Retry configuration for failed issues.',
    'retry:',
    '  maxAttempts: 3',
    '  backoffMinutes: 60',
    '',
    '# Auto-merge settings.',
    "mergeCommentTrigger: '/merge'",
    'mergeMethod: merge',
    'mergeDraftPRs: false',
    'autoMerge: true',
    'autoMergeRequireTests: true',
    '',
  ].join('\n')
}

function defaultCommandExists(command: string): boolean {
  const locator = process.platform === 'win32' ? 'where' : 'which'
  const result = spawnSync(locator, [command], { stdio: 'ignore' })
  return result.status === 0
}

function createPrompt(): { ask: (question: string) => Promise<string>; close: () => void } {
  return createInkPrompt()
}

function displayPath(cwd: string, targetPath: string): string {
  const relativePath = relative(cwd, targetPath)
  return relativePath === '' ? '.' : (relativePath.startsWith('..') ? targetPath : `./${relativePath}`)
}

function parseRepoInput(input: string): { owner: string; name: string } | undefined {
  const trimmed = input.trim()
  if (!trimmed) return undefined

  const urlMatch = trimmed.match(/github\.com[:/]([^/\s]+)\/([^/\s]+?)(?:\.git)?$/i)
  if (urlMatch?.[1] && urlMatch[2]) {
    return { owner: urlMatch[1], name: urlMatch[2] }
  }

  const slugMatch = trimmed.match(/^([^/\s]+)\/([^/\s]+)$/u)
  if (slugMatch?.[1] && slugMatch[2]) {
    return { owner: slugMatch[1], name: slugMatch[2].replace(/\.git$/i, '') }
  }

  return undefined
}

function parsePositiveInteger(input: string, fallback: number): number {
  const value = Number.parseInt(input.trim(), 10)
  return Number.isFinite(value) && value > 0 ? value : fallback
}

function buildRepoConfig(parsedRepo: { owner: string; name: string }, defaultBranch: string, testCommand: string): RepoConfig {
  const repo: RepoConfig = {
    owner: parsedRepo.owner,
    name: parsedRepo.name,
    defaultBranch,
  }

  if (testCommand !== '') {
    repo.testCommand = testCommand
  }

  return repo
}

async function askYesNo(
  prompt: (question: string) => Promise<string>,
  question: string,
  defaultValue: boolean,
): Promise<boolean> {
  const suffix = defaultValue ? ' [Y/n]: ' : ' [y/N]: '
  const answer = (await prompt(`${question}${suffix}`)).trim().toLowerCase()
  if (answer === '') return defaultValue
  return answer === 'y' || answer === 'yes'
}

async function promptForRepo(
  prompt: (question: string) => Promise<string>,
  output: Pick<Console, 'warn'>,
  question: string,
): Promise<{ owner: string; name: string }> {
  while (true) {
    const repoInput = await prompt(question)
    const parsedRepo = parseRepoInput(repoInput)
    if (parsedRepo) {
      return parsedRepo
    }

    output.warn('Enter a repository as owner/name or a GitHub URL.')
  }
}

async function collectRepos(
  prompt: (question: string) => Promise<string>,
  output: Pick<Console, 'warn'>,
): Promise<RepoConfig[]> {
  const repos: RepoConfig[] = []
  const seenRepos = new Set<string>()

  while (repos.length === 0) {
    const firstRepo = await promptForRepo(prompt, output, 'Paste a repository (owner/name or GitHub URL): ')

    const defaultBranch = (await prompt(`Default branch for ${firstRepo.owner}/${firstRepo.name} [main]: `)).trim() || 'main'
    const testCommand = (await prompt(`Test command for ${firstRepo.owner}/${firstRepo.name} [auto-detect]: `)).trim()
    const repoKey = `${firstRepo.owner}/${firstRepo.name}`.toLowerCase()
    if (seenRepos.has(repoKey)) {
      output.warn(`Skipping duplicate repository ${firstRepo.owner}/${firstRepo.name}.`)
      continue
    }

    repos.push(buildRepoConfig(firstRepo, defaultBranch, testCommand))
    seenRepos.add(repoKey)
  }

  while (await askYesNo(prompt, 'Add another repository?', false)) {
    const parsedRepo = await promptForRepo(prompt, output, 'Paste another repository (owner/name or GitHub URL): ')

    const defaultBranch = (await prompt(`Default branch for ${parsedRepo.owner}/${parsedRepo.name} [main]: `)).trim() || 'main'
    const testCommand = (await prompt(`Test command for ${parsedRepo.owner}/${parsedRepo.name} [auto-detect]: `)).trim()
    const repoKey = `${parsedRepo.owner}/${parsedRepo.name}`.toLowerCase()
    if (seenRepos.has(repoKey)) {
      output.warn(`Skipping duplicate repository ${parsedRepo.owner}/${parsedRepo.name}.`)
      continue
    }

    repos.push(buildRepoConfig(parsedRepo, defaultBranch, testCommand))
    seenRepos.add(repoKey)
  }

  return repos
}

async function collectAnswers(
  prompt: (question: string) => Promise<string>,
  output: Pick<Console, 'log' | 'warn'>,
): Promise<OnboardingAnswers> {
  output.log('')
  output.log('Minion configuration wizard')
  output.log('--------------------------')
  output.log('Minion uses MAP (multi-agent-pipeline) to process issues.')
  output.log('')

  const token = (await prompt('GitHub token with repo scope (leave blank to fill later): ')).trim() || undefined
  const repos = await collectRepos(prompt, output)
  const maxIssuesRaw = await prompt('Maximum issues per run [1]: ')

  const answers: OnboardingAnswers = {
    repos,
    maxIssuesPerRun: parsePositiveInteger(maxIssuesRaw, 1),
  }

  if (token !== undefined) {
    answers.token = token
  }

  output.log('')
  output.log('Configuration summary:')
  for (const repo of answers.repos) {
    output.log(`- ${repo.owner}/${repo.name} (${repo.defaultBranch ?? 'main'})`)
  }
  output.log(`- maxIssuesPerRun: ${answers.maxIssuesPerRun}`)

  return answers
}

function buildNonInteractiveDefaults(): OnboardingAnswers {
  return {
    repos: [{ owner: 'my-org', name: 'my-repo', defaultBranch: 'main' }],
    maxIssuesPerRun: 1,
  }
}

async function shouldWriteFile(
  targetPath: string,
  label: string,
  force: boolean,
  interactive: boolean,
  prompt: (question: string) => Promise<string>,
  output: Pick<Console, 'log'>,
): Promise<boolean> {
  if (!existsSync(targetPath)) return true
  if (force) return true
  if (!interactive) {
    output.log(`Kept existing ${label}`)
    return false
  }

  const overwrite = await askYesNo(prompt, `${label} already exists. Regenerate it?`, false)
  if (!overwrite) {
    output.log(`Kept existing ${label}`)
  }
  return overwrite
}

export async function runOnboarding(options: OnboardingOptions): Promise<number> {
  const cwd = resolve(options.cwd ?? process.cwd())
  const output = options.output ?? console
  const interactive = options.interactive ?? (Boolean(process.stdin.isTTY) && Boolean(process.stdout.isTTY))
  const configPath = resolve(cwd, options.configPath)
  const envPath = resolve(cwd, options.envPath ?? '.env')
  const commandExists = options.commandExists ?? defaultCommandExists
  const force = options.force ?? false

  output.log('Starting minion onboarding...')

  let promptHandle: { ask: (question: string) => Promise<string>; close: () => void } | undefined
  const prompt = options.prompt ?? ((question: string) => {
    if (!promptHandle) promptHandle = createPrompt()
    return promptHandle.ask(question)
  })

  try {
    const answers = interactive ? await collectAnswers(prompt, output) : buildNonInteractiveDefaults()

    const writeEnv = await shouldWriteFile(
      envPath,
      displayPath(cwd, envPath),
      force,
      interactive,
      prompt,
      output,
    )
    if (writeEnv) {
      mkdirSync(dirname(envPath), { recursive: true })
      writeFileSync(envPath, renderEnvTemplate(answers.token), 'utf-8')
      output.log(`Wrote ${displayPath(cwd, envPath)}`)
    }

    const writeConfig = await shouldWriteFile(
      configPath,
      displayPath(cwd, configPath),
      force,
      interactive,
      prompt,
      output,
    )
    if (writeConfig) {
      mkdirSync(dirname(configPath), { recursive: true })
      writeFileSync(configPath, renderConfigTemplate(answers), 'utf-8')
      output.log(`Wrote ${displayPath(cwd, configPath)}`)
    }

    const checks = [
      ['git', commandExists('git')],
      ['pnpm', commandExists('pnpm')],
      ['map', commandExists('map')],
    ] as const

    output.log('')
    output.log('Environment checks:')
    output.log(`- GITHUB_TOKEN: ${process.env['GITHUB_TOKEN'] || answers.token ? 'configured' : 'missing'}`)
    for (const [name, present] of checks) {
      output.log(`- ${name}: ${present ? 'found' : 'missing'}`)
    }

    output.log('')
    output.log('Next steps:')
    output.log(`1. Review ${displayPath(cwd, configPath)} and confirm the repository list.`)
    output.log(`2. Ensure the \`map\` binary is installed and on PATH.`)
    output.log(`3. Add GITHUB_TOKEN to ${displayPath(cwd, envPath)} if it is still blank.`)
    output.log(`4. Run \`pnpm start -- --config ${displayPath(cwd, configPath)}\` from this repo, or \`minion --config ${displayPath(cwd, configPath)}\` if installed globally.`)

    return 0
  } finally {
    if (promptHandle) {
      promptHandle.close()
    }
  }
}
